ProyectEmpleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('', include('apps.empleado.urls')),
    path('', include('apps.departamento.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "departamento_app"
urlpatterns = [
    path(
        'departamento-lista/',
        views.DepartamentoListView.as_view(),
        name='departamento-lista'),
    path(
        'new-departamento/',
        views.NewDepartamentoView.as_view(),
        name='nuevo_departamento'),

]

apps/empleado/urls.py
from django.urls import path
from . import views

app_name = 'empleado_app'
urlpatterns = [
    path('',
         views.InicioView.as_view(),
         name='inicio'),
    path(
        'listarAllEmpleados/',
        views.ListaAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path('list-by-area/<short_name>/',
         views.ListByAreaEmpleado.as_view(),
         name='empleados_area'),
    path('lista-empleados-admin/',
         views.ListaEmpleadosAdmin.as_view(),
         name='empleados_admin'),
    path('buscar-empleado/', views.ListEmpleadoByKword.as_view()),
    path('habilidades/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver_empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add_empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'),
    path('succes/', views.SuccesView.as_view(), name='correcto'),
    path(
        'update_empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'),
    path('delete-empleado/<pk>/',
         views.EmpleadoDeleteView.as_view(),
         name='eliminar_empleado')
]

templates/includes/header.html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Empleados</li>
      <li>
        <a href="{% url 'empleado_app:empleados_all' %}">Listar</a>
      </li>
      <li><a href="{% url 'departamento_app:departamento-lista' %}">Departamentos</a></li>
      <li><a href="{% url 'empleado_app:empleados_admin' %}">Administrar</a></li>
      <li><a href="{% url 'departamento_app:nuevo_departamento' %}">Nuevo departamento</a></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Buscar empleado"></li>
      <li><a href="{% url 'empleado_app:empleado_add' %}" type="button" class="button">Registrar Nuevo</a></li>
    </ul>
  </div>
</div>