ProyectEmpleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('', include('apps.empleado.urls')),
    path('', include('apps.departamento.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "departamento_app"
urlpatterns = [
    path(
        'departamento-lista/',
        views.DepartamentoListView.as_view(),
        name='departamento-lista'),
    path(
        'new-departamento/',
        views.NewDepartamentoView.as_view(),
        name='nuevo_departamento'),

]

apps/empleado/urls.py
from django.urls import path
from . import views

app_name = 'empleado_app'
urlpatterns = [
    path('',
         views.InicioView.as_view(),
         name='inicio'),
    path(
        'listarAllEmpleados/',
        views.ListaAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path('list-by-area/<short_name>/',
         views.ListByAreaEmpleado.as_view(),
         name='empleados_area'),
    path('lista-empleados-admin/',
         views.ListaEmpleadosAdmin.as_view(),
         name='empleados_admin'),
    path('buscar-empleado/', views.ListEmpleadoByKword.as_view()),
    path('habilidades/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver_empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add_empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'),
    path('succes/', views.SuccesView.as_view(), name='correcto'),
    path(
        'update_empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'),
    path('delete-empleado/<pk>/',
         views.EmpleadoDeleteView.as_view(),
         name='eliminar_empleado')
]

apps/departamento/models.py
from django.db import models


# Create your models here.
class Departamento(models.Model):
    nombre = models.CharField(max_length=50, verbose_name='Nombre')
    short_name = models.CharField(max_length=20, verbose_name='Nombre corto')
    anulate = models.BooleanField(verbose_name='Anulado', default=False)

    class Meta:
        verbose_name = 'Departamento',
        verbose_name_plural = 'Departamentos'
        ordering = ['-nombre']
        unique_together = ('nombre', 'short_name')

    def __str__(self):
        return '%s - %s' % (self.nombre, self.short_name)

apps/departamento/forms.py
from django import forms


class NewDepartamentoForm(forms.Form):
    name = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50)
    short_name = forms.CharField(max_length=50)

apps/departamento/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import FormView
from .forms import NewDepartamentoForm
# Create your views here.
from ..empleado.models import Empleado
from .models import Departamento


class DepartamentoListView(ListView):
    model = Departamento
    template_name = 'departamento/lista.html'
    context_object_name = 'departamentos'


class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        nombre = form.cleaned_data['name']
        apellido = form.cleaned_data['apellidos']
        depa = Departamento(
            nombre=form.cleaned_data['departamento'],
            short_name=form.cleaned_data['short_name']
        )
        depa.save()
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellido,
            job='1',
            departamento=depa
        )
        return super(NewDepartamentoView, self).form_valid(form)

templates/departamento/lista.html
{% extends 'base.html' %}
{% block title %}
  Lista departamento
{% endblock title %}
{% block content %}
  {% include 'includes/header.html'%}
  <div class="grid-container">
    <div class="grid-x">
      <h1 class="cell">
        Lista departamentos
      </h1>
      <div class="cell">
        <table>
          <tbody>
            {% for departamento in departamentos%}
            <tr>
              <td>{{departamento.nombre}}</td>
              <td>{{departamento.short_name}}</td>
              <td>
                <a class="button warning" href="{% url 'empleado_app:empleados_area' departamento.short_name %} ">Ver empleados</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock content %}

templates/departamento/new_departamento.html
{% extends 'base.html' %}
{% block title %}
Registrar departamento
{% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">Registrar Departamento</h1>
    <form class="cell callout grid-x grid-margin-x" method="POST">{% csrf_token %}
      <div class="medium-6 cell">
        <label>Nombres:
            {{form.name}}
        </label>
      </div>
      <div class="medium-6 cell">
        <label>Apellidos:
            {{form.apellidos}}
        </label>
      </div>
      <div class="medium-6 cell">
        <label>Apellidos:
            {{form.departamento}}
        </label>
      </div>
      <div class="medium-6 cell">
        <label>Apellidos:
            {{form.short_name}}
        </label>
      </div>
      <div class="medium-6 cell">
        <button type="submit" class="button">Guardar</button>
      </div>
    </form>
  </div>
</div>
{% endblock content %}