ProyectEmpleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('', include('apps.empleado.urls')),
    path('', include('apps.departamento.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/empleado/urls.py
from django.urls import path
from . import views

app_name = 'empleado_app'
urlpatterns = [
    path('',
         views.InicioView.as_view(),
         name='inicio'),
    path(
        'listarAllEmpleados/',
        views.ListaAllEmpleados.as_view(),
        name='empleados_all'
    ),
    path('list-by-area/<short_name>/',
         views.ListByAreaEmpleado.as_view(),
         name='empleados_area'),
    path('lista-empleados-admin/',
         views.ListaEmpleadosAdmin.as_view(),
         name='empleados_admin'),
    path('buscar-empleado/', views.ListEmpleadoByKword.as_view()),
    path('habilidades/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver_empleado/<pk>/',
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add_empleado/',
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'),
    path('succes/', views.SuccesView.as_view(), name='correcto'),
    path(
        'update_empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'),
    path('delete-empleado/<pk>/',
         views.EmpleadoDeleteView.as_view(),
         name='eliminar_empleado')
]

apps/empleado/models.py
from django.db import models
from apps.departamento.models import Departamento


class Habilidades(models.Model):
    habilidad = models.CharField(verbose_name='Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades'

    def __str__(self):
        return '%s' % self.habilidad


# Create your models here.
class Empleado(models.Model):

    JOB_CHOICES = (
        ('0', 'Contador'),
        ('1', 'Administrador'),
        ('2', 'Economista'),
        ('3', 'Otro')
    )
    first_name = models.CharField(max_length=60, verbose_name='Primer nombre')
    last_name = models.CharField(max_length=60, verbose_name='Apellido')
    job = models.CharField(verbose_name='Trabajo', max_length=1, choices=JOB_CHOICES)
    full_name = models.CharField(verbose_name='Nombre completo',
                                 max_length=120,
                                 blank=True)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    # image = models.ImageField

    def __str__(self):
        return '%s - %s' % (self.first_name, self.last_name)

    class Meta:
        verbose_name = 'Mi Empleo'
        verbose_name_plural = 'Empleados de la empresa'
        ordering = ['-first_name', 'last_name']
        unique_together = ('first_name', 'departamento')

apps/empleado/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields = [
            'first_name',
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        ]
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple(

            )
        }

apps/empleado/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView, DeleteView
)
# Create your views here.
from .models import Empleado
from .forms import EmpleadoForm


class InicioView(TemplateView):
    """ vista que carga la pagina de inicio """
    template_name = 'index.html'


class ListaAllEmpleados(ListView):
    template_name = 'empleado/list_all.html'
    paginate_by = 4
    context_object_name = 'lista'

    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '')
        queryset = Empleado.objects.filter(
            full_name__icontains=palabra_clave
        )
        return queryset


class ListaEmpleadosAdmin(ListView):
    template_name = 'empleado/lista_empleados.html'
    paginate_by = 10
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado


class ListByAreaEmpleado(ListView):
    template_name = 'empleado/list_by_area.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        area = self.kwargs['short_name']
        queryset = Empleado.objects.filter(
            departamento__short_name=area
        )
        return queryset


class ListEmpleadoByKword(ListView):
    template_name = 'empleado/by_kword.html'
    context_object_name = 'empleados'

    def get_queryset(self):
        palabra_clave = self.request.GET.get('kword', '')
        queryset = Empleado.objects.filter(
            first_name=palabra_clave
        )
        return queryset


class ListHabilidadesEmpleado(ListView):
    template_name = 'empleado/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        empleado = Empleado.objects.get(id=1)
        habilidades = empleado.habilidades.all()
        return habilidades


class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = 'empleado/detail_empleado.html'

# 1 - Lista todos los empleados de la empresa
# 2 - Listar todos los empleados que pertenecen al area de la empresa
# 3 - Listar empleados por palabra clave
# 4 - Listar habilidades de un empleado


class SuccesView(TemplateView):
    template_name = 'empleado/succes.html'


# Nambre, hasta se crea el html
class EmpleadoCreateView(CreateView):
    template_name = "empleado/add.html"
    model = Empleado
    form_class = EmpleadoForm
    # success_url = '.'  Redirije a la misma pagina
    success_url = reverse_lazy('empleado_app:empleados_admin')

    def form_valid(self, form):
        # Logica del proceso
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)


class EmpleadoUpdateView(UpdateView):
    template_name = 'empleado/update.html'
    model = Empleado
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades'
    ]
    success_url = reverse_lazy('empleado_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print('**************METODO POST***************')
        print('===============================================')
        print(request.POST)
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        # Logica del proceso
        print('**************METODO Form valida***************')

        return super(EmpleadoUpdateView, self).form_valid(form)


class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = 'empleado/delete.html'
    success_url = reverse_lazy('empleado_app:empleados_admin')

templates/empleado/add.html
{% extends 'base.html' %}
{% block title %}
Registrar Empleado
{% endblock title %}
{% block content %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres:
                   {{form.first_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                   {{form.last_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Trabajo:
                   {{form.job}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                   {{form.departamento}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Habilidades:
                   {{form.habilidades}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Avatar:
                   {{form.avatar}}
                </label>
            </div>
            <div class="medium-6 cell">
                <button type="submit" class="button success">Agregar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/empleado/by_kword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Buscar por palabra clave</h1>
    <form action="" method="get">{% csrf_token %}
      <input type="text" name="kword" id="kword" placeholder="Ingrese su nombre aqui">
      <input type="submit" value="Buscar">
    </form>
    <h3>Lista resultados</h3>
    <ul>
        {% for empleado in empleados%}
            <li>{{empleado}}</li>
        {% endfor %}
    </ul>
</body>
</html>

templates/empleado/delete.html
{% extends 'base.html' %}
{% block title %}
Eliminar empleado
{% endblock title%}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar Empleado: {{object.full_name}}</h1>
        <form class='cell' method="POST">{% csrf_token %}
            <div class="callout secondary">
                <h5>¿Desea eliminar este empleado?</h5>
                <button type="submit" class="alert button">Confirmar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/empleado/detail_empleado.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{object.full_name}}
{% endblock title %}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell large-4" style="width: 300px;">
            <div class="card-divider">
                {{empleado.get_job_display}}
            </div>
            {% if empleado.avatar%}
            <img src="{{empleado.avatar.url}}">
            {% else %}
            <img src="{% static 'img/evento.avif'%}">
            {% endif %}
            <div class="card-section">
                <h4>{{object.full_name}}</h4>
                <p>{{empleado.first_name}}</p>
                <p>{{empleado.departamento.short_name}}</p>
                <p><span class="label">Habilidades</span></p>
                <ul class="vertical menu">
                    {% for habilidad in empleado.habilidades.all %}
                        <li>{{habilidad}}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock content%}

templates/empleado/habilidades.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Habilidades</h1>
    <ul>
      {% for habilidad in habilidades%}
        <li>{{habilidad}}</li>
      {% endfor %}
    </ul>
</body>
</html>

templates/empleado/list_all.html
{% extends 'base.html' %}
{% block content %}
{% include 'includes/header.html'%}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET">{% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                <tr>
                    <th width="200">Id</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCION</th>
                </tr>
                </thead>
                <tbody>
                {% for e in object_list %}
                <tr>
                    <td>{{e.id}}</td>
                    <td>{{e.first_name}}</td>
                    <td>{{e.last_name}}</td>
                    <td>{{e.departamento}}</td>
                    <td><a class="button warning" href="{% url 'empleado_app:empleado_detail' e.id %}">Ver</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="cell">
        {% if is_paginated%}
        <nav aria-label="Pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="pagination-previous">
                    <a href="?page={{page_obj.previous_page_number}}">
                        Anterior
                    </a>
                </li>
                {% endif %}
                {% for pagina in paginator.page_range %}
                {% if pagina == page_obj.number %}
                 <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>
                    {% else %}
                <li><a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a></li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next%}
                <li class="pagination-next">
                    <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}

    </div>
</div>

{% endblock content %}

templates/empleado/list_by_area.html
{% extends 'base.html' %}
{% block title %}
Lista empleados por departamento
{% endblock title %}
{% block content %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <div class="cell">Empleados por area:</div>
        <div class="cell">
            <table>
                <thead>
                <tr>
                    <th width="200">Id</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCION</th>
                </tr>
                </thead>
                <tbody>
                {% for e in object_list %}
                <tr>
                    <td>{{e.id}}</td>
                    <td>{{e.first_name}}</td>
                    <td>{{e.last_name}}</td>
                    <td>{{e.departamento}}</td>
                    <td><a class="button warning" href="{% url 'empleado_app:empleado_detail' e.id %}">Ver</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}
<h1>Listado por area</h1>
<ul>
    {% for area in object_list %}
    <li>{{area}}</li>
    {% endfor %}
</ul>

templates/empleado/lista_empleados.html
{% extends 'base.html' %}
{% block content %}
{% include 'includes/header.html'%}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <div class="cell">
            <table>
                <thead>
                <tr>
                    <th width="200">Id</th>
                    <th>NOMBRES</th>
                    <th width="150">APELLIDOS</th>
                    <th width="150">DEPARTAMENTO</th>
                    <th width="150">ACCION</th>
                </tr>
                </thead>
                <tbody>
                {% for e in object_list %}
                <tr>
                    <td>{{e.id}}</td>
                    <td>{{e.first_name}}</td>
                    <td>{{e.last_name}}</td>
                    <td>{{e.departamento}}</td>
                    <td>
                        <a class="button success" href="{% url 'empleado_app:modificar_empleado' e.id%}">Editar</a>
                    </td>
                    <td>
                        <a class="button alert" href="{% url 'empleado_app:eliminar_empleado' e.id%}">Eliminar</a>
                    </td>

                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="cell">
        {% if is_paginated%}
        <nav aria-label="Pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="pagination-previous">
                    <a href="?page={{page_obj.previous_page_number}}">
                        Anterior
                    </a>
                </li>
                {% endif %}
                {% for pagina in paginator.page_range %}
                {% if pagina == page_obj.number %}
                 <li class="current"><span class="show-for-sr">You're on page</span> {{pagina}}</li>
                    {% else %}
                <li><a href="?page={{pagina}}" aria-label="Page 2">{{pagina}}</a></li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next%}
                <li class="pagination-next">
                    <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}

    </div>
</div>

{% endblock content %}

templates/empleado/succes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>Felicitaciones, se guardo correctamente el empleado</h1>
</body>
</html>

templates/empleado/update.html
{% extends 'base.html' %}
{% block title %}
Editar Empleado
{% endblock title%}
{% block content %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar Empleado
        </h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres:
                        {{form.first_name}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Apellidos:
                        {{form.last_name}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Trabajo:
                        {{form.job}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Area:
                        {{form.departamento}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades extra:
                        {{form.habilidades}}
                    </label>
                </div>
                <div class="cell">
                     <button type="submit" class="success button">Actualizar</button>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock content %}